name: Production Deployment

# on:
#   push:
#     branches:
#       - main

on: [push]

env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT_NAME: ${{ secrets.SERVICE_ACCOUNT_NAME }}
  IMAGE_URL: ${{ secrets.IMAGE_URL }}:${{ github.sha }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  REGION: ${{ secrets.REGION }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    ## build docker image and push image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

    ## 
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_NAME }}
          access_token_lifetime: '300s'
      # This example uses the docker login action
      - uses: 'docker/login-action@v1'
        with:
          registry: '${{ env.REGION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      - run: echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://${{ env.REGION }}-docker.pkg.dev


      # - id: 'auth'
      #   name: 'auth gcp'
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     # 事前準備で作成した`Workload Identity Providerのリソース名`と`Service Account`を指定する
      #     workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      #     service_account: ${{ secrets.SERVICE_ACCOUNT_NAME }}

      # - id: 'setup'
      #   name: 'Setup Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v0'

      # - name: 'Authorize Docker push'
      #   # Artifact Registryにpushできるように認証行う
      #   # Container Registryのときには不要だったArtifact RegistryではRegionの指定が必須
      #   run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build Docker Image
        run: |-
          docker build -t local/image --build-arg ENV="production" ./
          docker tag local/image ${{ env.IMAGE_URL }}
      
      # - id: 'deploy'
      #   uses: 'google-github-actions/deploy-cloudrun@v1'
      #   with:
      #     service: ${{ env.SERVICE_NAME }}
      #     image: ${{ env.IMAGE_URL }}

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_URL }}

      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v1'
      # - name: 'check gcloud init'
      #   run: gcloud config list

      # - name: deploy into cloud run
      #   run: gcloud run deploy ${{ env.SERVICE_NAME }} --image ${{ env.IMAGE_URL }} --region ${{ env.REGION }}

      - uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
      - name: 'Deploy Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.IMAGE_URL }}
          region: ${{ env.REGION }}
