name: Production Deployment

# on:
#   push:
#     branches:
#       - main

on: [push]

env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT_NAME: ${{ secrets.SERVICE_ACCOUNT_NAME }}
  IMAGE_URL: ${{ secrets.IMAGE_URL }}:${{ github.sha }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    ## build docker image and push image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT_NAME }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      # - id: 'setup'
      #   name: 'Setup Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v0'

      # - name: 'Authorize Docker push'
        # Artifact Registryにpushできるように認証行う
        # Container Registryのときには不要だったArtifact RegistryではRegionの指定が必須
        # run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build Docker Image
        run: |-
          docker build -t local/image --build-arg ENV="production" ./
          docker tag local/image ${{ env.IMAGE_URL }}
      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_URL }}

      - name: deploy into cloud run
        run: gcloud run deploy ${{ env.SERVICE_NAME }} --image ${{ env.IMAGE_URL }}
